"""
Django settings for site_repo project.

Generated by 'django-admin startproject' using Django 1.8.1.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""
import logging
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MEDIA_ROOT = "%s/media_root/"%BASE_DIR
STATIC_ROOT = "%s/static_root/"%BASE_DIR
TEMPLATE_DIRS = ["%s/templates/"%os.path.dirname(os.path.abspath(__file__))]

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'I_AM_NOT_SECRET_PLEASE_REPLACE_ME_SEE_README'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# Debug logging, consider preformance
# Application logs are found in project-dir/logs. On production see /home/django/projectname/logs/
# For temporary debug logging, add DEBUG_LOG = True, or DEBUG_DB_LOG = True, to site_config/settings_tmp.py, and reload

# if True, logs all logging.debug() statements, saved to to debug.log, and catch other logs. Otherwise ignores
DEBUG_LOG = True 

# django auto logger of all the code-to-database interactions. Saved to debug_db.logs
DEBUG_DB_LOG = False

ALLOWED_HOSTS = ['127.0.0.1','localhost']


# Application definition

INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'site_repo.home'
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'site_repo.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': TEMPLATE_DIRS,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'site_repo.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'django_db',
        'USER': 'django',
        'PASSWORD':'imnotsecretdjangomysqlpassword',
        'HOST': '127.0.0.1',
        'PORT': 3306
    }
}


# Internationalization
# https://docs.djangoproject.com/en/1.8/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'


# Check if the repository public secret, and mysql password, were replaced
if SECRET_KEY == 'I_AM_NOT_SECRET_PLEASE_REPLACE_ME_SEE_README':
    raise ImproperlyConfigured("Change the SECRET_KEY in settings, see README")

if DATABASES['default']['PASSWORD'] == 'imnotsecret' + 'djangomysqlpassword':
    raise ImproperlyConfigured("Change the django user password to MySQL, see README")



# Allows a temp settings file, for dev, ad hoc logging etc
try:
    from site_config.settings_tmp import *
except:
    pass


# Production settings, available only on production
try:
    from site_config.settings_production import *
except:
    pass



# Logging:

# debug log filters, after import, to allow changes by settings_production, settings_tmp
class RequireDebugLogTrue(logging.Filter):
    def filter(self, record):
        return DEBUG_LOG    
class RequireDebugDBLogTrue(logging.Filter):
    def filter(self, record):
        return DEBUG_DB_LOG
    
# Config loggers
# Added debug.log and main.log to django defaults, will log by the DEBUG_LOG, DEBUG_DB_LOG settings, see above
# Log to debug.log:  logging.debug('some debugging msg')
# Log to main.log: logging.getLogger('main').info('important production msg')
# main.log accepts info and higher levels
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'filters': {
        'require_debug_false': {
            '()': 'django.utils.log.RequireDebugFalse',
        },
        'require_debug_true': {
            '()': 'django.utils.log.RequireDebugTrue',
        },
        'require_debug_log_true': {
            '()': RequireDebugLogTrue,
            },  
        'require_debug_db_log_true': {
            '()': RequireDebugDBLogTrue,
            },         
    },
    'handlers': {
        'default': {
            'level': 'DEBUG',
            'class': 'logging.handlers.RotatingFileHandler',
            'filters': ['require_debug_log_true'],
            'filename': "%s/logs/debug.log"%BASE_DIR,
            'maxBytes': 1024*1024*5,
            'backupCount':7,
            },
        'main': {
            'level': 'INFO',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': "%s/logs/main.log"%BASE_DIR,
            'maxBytes': 1024*1024*5,
            'backupCount':7,
            },
        'django_db': {
            'level': 'DEBUG',
            'class': 'logging.handlers.RotatingFileHandler',
            'filters': ['require_debug_db_log_true'],
            'filename': "%s/logs/debug_db.log"%BASE_DIR,
            'maxBytes': 1024*1024*5,
            'backupCount':7,
            },        
        'console': {
            'level': 'INFO',
            'filters': ['require_debug_true'],
            'class': 'logging.StreamHandler',
        },
        'mail_admins': {
            'level': 'ERROR',
            'filters': ['require_debug_false'],
            'class': 'django.utils.log.AdminEmailHandler'
        }
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'mail_admins'],
            'propagate':True
        },
        'py.warnings': {
            'handlers': ['console'],
            'propagate':True
        },
        '': {
            'handlers': ['default'],
            'propagate':True
            },
        'main': {
            'handlers': ['main'],
            'propagate':True
            },
        'django.db.backends': {
            'handlers': ['django_db'],
            'propagate':False
            },         
    }
}






